[package]
name = "tonic"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.3.1"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/tonic/0.3.1/tonic/"
repository = "https://github.com/hyperium/tonic"
homepage = "https://github.com/hyperium/tonic"
description = """
A gRPC over HTTP/2 implementation focused on high performance, interoperability, and flexibility.
"""
readme = "../README.md"
categories = ["web-programming", "network-programming", "asynchronous"]
keywords = ["rpc", "grpc", "async", "futures", "protobuf"]

[features]
default = ["transport", "codegen", "prost"]
codegen = ["async-trait"]
transport = [
    "hyper",
    "tokio",
    "tower",
    "tracing-futures",
]
tls = ["transport", "tokio-rustls"]
tls-roots = ["tls", "rustls-native-certs"]
prost = ["prost1", "prost-derive"]

# [[bench]]
# name = "bench_main"
# harness = false

[dependencies]
bytes = "0.6"
futures-core = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }
tracing = "0.1"
http = "0.2"
base64 = "0.12"

percent-encoding = "2.0"
tower-service = "0.3"
tokio-util = { version = "0.5", features = ["codec"] }
async-stream = "0.2"
http-body = { git = "https://github.com/hyperium/http-body", branch = "master" }
pin-project = "0.4.17"

# prost
prost1 = { package = "prost", optional = true, git = "https://github.com/danburkert/prost", branch = "master" }
prost-derive = { optional = true, git = "https://github.com/danburkert/prost", branch = "master" }

# codegen
async-trait = { version = "0.1.13", optional = true }

# transport
hyper = { git = "https://github.com/hyperium/hyper", branch = "master", features = ["full"], optional = true }
tokio = { version = "0.3.2", features = ["net", "sync"], optional = true }
tracing-futures = { version = "0.2", optional = true }

# rustls
tokio-rustls = { version = "0.20", optional = true }
rustls-native-certs = { version = "0.4", optional = true }

[dependencies.tower]
git = "https://github.com/tower-rs/tower"
version = "0.4"
features = ["balance", "load", "make", "buffer", "limit", "util", "timeout"]
optional = true

[dev-dependencies]
tokio = { version = "0.3", features = ["rt", "macros"] }
static_assertions = "1.0"
rand = "0.7"
bencher = "0.1.5"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "decode"
harness = false

